### ISSUE TITLE
RAP version which support jboss8 and openjdk17

### ISSUE THREAD

**Issue by Devip-singh** [eclipse-rap/org.eclipse.rap#108]
Hello Team,

Currently we are using jboss7.4 with openjdk8. RAP version used is 3.10 . **_Please suggest RAP version which is compatible with jboss8 and openjdk17 . We would like to migrate to that version._**

**Comment by ifurnadjiev** [comment]
By fast reading JBoss 8 is based on Jakarta EE 9 API. Currently, RAP still doesn't support containers based on this specification. See issue #73. RAP is compatible with Open JDK 17.

**Comment by Devip-singh** [comment]
Thanks for so prompt response !!

Jboss8 is based on Jakarta EE 10 API . Could you please help to know the version/versions compatible with openjdk 17.
I did not get it in news and noteworthy list.

**Comment by ifurnadjiev** [comment]
Latest RAP released version 3.23 is compatible with Open JDK 17, but lower versions are also compatible.

**Comment by Devip-singh** [comment]
@ifurnadjiev 
Do you have idea about timeline when RAP will be compatible with Jakarta ee 10 ?

**Comment by ifurnadjiev** [comment]
@Devip-singh the problem is not only about RAP framework, but all connected Eclipse projects from the Eclipse platform. I hope that for the June release (3.25) all the Eclipse project will move to Jakarta API. But there is no guarantee.

**Comment by Devip-singh** [comment]
@ifurnadjiev 
I can see 3.25 is available but did not found any information about its compatibility with Jakarta api . I checked news but no information available on Jakarta. Please let me know if you have something on this.
Thanks again for all your help so far !!

**Comment by mknauer** [comment]
Correct, we published RAP 3.25 last week.  
Like the entire Eclipse Simultaneous Release 2023-06, most bundles of Eclipse RAP require a Java 17 as a minimum requirement, and again like the entire Eclipse Simultaneous Release, still use the `javax.servlet` namespace and the associated Servlet specification. Ultimately, however, I am not aware of any plan as to when the Eclipse Platform and also the Simultaneous Release will implement these changes. Again, as RAP project I'd like to see this rather sooner than later.

Our wish is to move to the JakartaEE namespace as soon as possible, at least for Eclipse RAP, and also to have a version that is as compatible as possible for the newer Servlet specification versions. 

Since this means major changes in RAP, we are dependent on external sponsorship for this development and a few of our customers with our commercial [developer support](https://eclipsesource.com/services/developer-support/) have already shown interest. If sponsorship is a way forward for you, then we might have one or two ideas for a solution. Then the best thing is to contact us via the contact form on our [support website](https://eclipsesource.com/services/developer-support/).

**Comment by jose68** [comment]
> Correct, we published RAP 3.25 last week. Like the entire Eclipse Simultaneous Release 2023-06, most bundles of Eclipse RAP require a Java 17 as a minimum requirement, and again like the entire Eclipse Simultaneous Release, still use the `javax.servlet` namespace and the associated Servlet specification. Ultimately, however, I am not aware of any plan as to when the Eclipse Platform and also the Simultaneous Release will implement these changes. Again, as RAP project I'd like to see this rather sooner than later.
> 
> Our wish is to move to the JakartaEE namespace as soon as possible, at least for Eclipse RAP, and also to have a version that is as compatible as possible for the newer Servlet specification versions.
> 
> Since this means major changes in RAP, we are dependent on external sponsorship for this development and a few of our customers with our commercial [developer support](https://eclipsesource.com/services/developer-support/) have already shown interest. If sponsorship is a way forward for you, then we might have one or two ideas for a solution. Then the best thing is to contact us via the contact form on our [support website](https://eclipsesource.com/services/developer-support/).

Hello, 
There are also plans to fully migrate all applications for example : https://github.com/eclipse-rap/org.eclipse.rap/blob/main/bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/engine/RWTServlet.java  from javax.* to jakarta.* ? 
Is yes, when is it planned ? 
Thanks in advance for your answer
